# Generated by Django 5.1.1 on 2024-10-08 19:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В процессе'), ('FINISHED', 'Завершено')], default='PENDING', max_length=128, verbose_name='Статус')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('total', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Общая стоимость')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Отчет по арендной плате дома',
                'verbose_name_plural': 'Отчеты по арендным плате домов',
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость')),
                ('billing_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingreport')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flat', verbose_name='Квартира')),
            ],
        ),
    ]
