# Generated by Django 5.1.1 on 2024-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(max_length=128, verbose_name='Номер'),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('house', 'number')},
        ),
    ]
